### ISSUE TITLE
CAN frame, error code: -1, errno: 105

### ISSUE THREAD

**Issue by andreadelprete** [open-dynamic-robot-initiative/blmc_drivers#16]
Hi guys, I am getting the following error when trying to communicate with the robot:
```
WARNING: Something went wrong with sending CAN frame, error code: -1, errno: 105. Possibly you have been attempting to send at a rate which is too high. We keep trying
waiting for board and motors to be ready 
```
Any idea what the problem should be?
I've already tried reducing the communication rate (from 1 kHz to 100 Hz) but that didn't solve the issue.
I'm currently using a leg of Solo with TI boards. I'm quite sure the hardware is find because it was working with the previous version of the software (with ros 1). Now I'm trying to make it work with the latest version of the software stack.

**Comment by jviereck** [comment]
(Leaving a comment here in case someone else comes across this).

Apparently the problem could be solved by increasing the sending queue size using this command [1]

```
sudo ifconfig can0 txqueuelen 1000
```

Closing issue as the problem was resolved using the above command.


[1]: https://stackoverflow.com/questions/40424433/write-no-buffer-space-available-socket-can-linux-can
