### ISSUE TITLE
 Easy CAN timeout problem

### ISSUE THREAD

**Issue by laniakeawhite** [open-dynamic-robot-initiative/blmc_drivers#26]
I am doing single motor test using "demo_sine_pos_1_motor".
As far as i know,the demo code “demo_2_motors” of blmc_drivers is a demo to control motor track the slide pos using PD.

If i hold the motor to make it can’t spin when “demo_2_motors” running, soon i will receive an error which error code=2( 2 means can recv timeout).

Is this normal or abnormal？

**Comment by luator** [comment]
Hi, are you running the demo on a machine with a real-time capable Linux kernel (ideally preempt_rt but the much more easy to install "lowlatency" kernel is probably enough)?  If not, this is expected.

The motor board expects new commands via CAN at a fixed rate.  If the next command is delayed by too much (not sure right now what the default is, I think a few milliseconds), the board stops with this error.  This is mostly to make sure the motors stop in case the connection is lost but on a normal (i.e. non-real-time) system, delays caused by the process scheduler can already be long enough to trigger this timeout.

If not already done, I suggest you install the lowlatency kernel (on Ubuntu simply with `apt install linux-lowlatency`, then reboot and select the kernel in the boot menu) and try if this fixes the error.
